/* ============================================
   src/constants/themes.ts
   DATA TEMA RABIKU.COM
   ============================================ */

export interface Theme {
  id: number;
  title: string;
  slug: string | null;
  price: string;
  tema: string;
  warna: string;
  image: string;
}

export const themes: Theme[] = [
  {
    id: 1,
    title: "Angelicgrace",
    slug: "elvano-azelia",
    price: "Rp 80.000",
    tema: "islamic",
    warna: "coklat",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 2,
    title: "Auroraromance",
    slug: "arka-kirana",
    price: "Rp 80.000",
    tema: "islamic",
    warna: "biru",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 3,
    title: "Aventianlovestory",
    slug: null,
    price: "Rp 80.000",
    tema: "islamic",
    warna: "pink",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 4,
    title: "Mysticdusk",
    slug: null,
    price: "Rp 80.000",
    tema: "islamic",
    warna: "ungu",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 5,
    title: "Celestialvow",
    slug: null,
    price: "Rp 80.000",
    tema: "islamic",
    warna: "hijau",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 6,
    title: "Nurani",
    slug: null,
    price: "Rp 80.000",
    tema: "islamic",
    warna: "coklat",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 7,
    title: "Rahma",
    slug: null,
    price: "Rp 80.000",
    tema: "islamic",
    warna: "biru",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 8,
    title: "Dreamycoastalarch",
    slug: null,
    price: "Rp 80.000",
    tema: "modern",
    warna: "hijau",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 9,
    title: "Velvetmoonlight",
    slug: null,
    price: "Rp 80.000",
    tema: "modern",
    warna: "ungu",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 10,
    title: "Rusticcharm",
    slug: null,
    price: "Rp 80.000",
    tema: "modern",
    warna: "coklat",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 11,
    title: "Urbanbliss",
    slug: null,
    price: "Rp 80.000",
    tema: "modern",
    warna: "biru",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 12,
    title: "Minimaluxe",
    slug: null,
    price: "Rp 80.000",
    tema: "modern",
    warna: "pink",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 13,
    title: "Monochromatica",
    slug: null,
    price: "Rp 80.000",
    tema: "modern",
    warna: "hijau",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 14,
    title: "Futuristicvow",
    slug: null,
    price: "Rp 80.000",
    tema: "modern",
    warna: "ungu",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 15,
    title: "Sereneblossom",
    slug: null,
    price: "Rp 80.000",
    tema: "minimalis",
    warna: "biru",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 16,
    title: "Whisperingsoul",
    slug: null,
    price: "Rp 80.000",
    tema: "minimalis",
    warna: "pink",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 17,
    title: "Pristinewhite",
    slug: null,
    price: "Rp 80.000",
    tema: "minimalis",
    warna: "coklat",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 18,
    title: "Softaura",
    slug: null,
    price: "Rp 80.000",
    tema: "minimalis",
    warna: "hijau",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 19,
    title: "Cleanslate",
    slug: null,
    price: "Rp 80.000",
    tema: "minimalis",
    warna: "ungu",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 20,
    title: "Barebeauty",
    slug: null,
    price: "Rp 80.000",
    tema: "minimalis",
    warna: "biru",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 21,
    title: "Goldenopulence",
    slug: null,
    price: "Rp 80.000",
    tema: "mewah",
    warna: "hijau",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 22,
    title: "Royalvelvet",
    slug: null,
    price: "Rp 80.000",
    tema: "mewah",
    warna: "ungu",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 23,
    title: "Crystalgrand",
    slug: null,
    price: "Rp 80.000",
    tema: "mewah",
    warna: "biru",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 24,
    title: "Majesticgold",
    slug: null,
    price: "Rp 80.000",
    tema: "mewah",
    warna: "coklat",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 25,
    title: "Imperialbloom",
    slug: null,
    price: "Rp 80.000",
    tema: "mewah",
    warna: "pink",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 26,
    title: "Regalcharm",
    slug: null,
    price: "Rp 80.000",
    tema: "mewah",
    warna: "hijau",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 27,
    title: "Woodlandwhisper",
    slug: null,
    price: "Rp 80.000",
    tema: "rustic",
    warna: "coklat",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 28,
    title: "Vintagebloom",
    slug: null,
    price: "Rp 80.000",
    tema: "rustic",
    warna: "pink",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 29,
    title: "Earthencharm",
    slug: null,
    price: "Rp 80.000",
    tema: "rustic",
    warna: "hijau",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 30,
    title: "Timberlove",
    slug: null,
    price: "Rp 80.000",
    tema: "rustic",
    warna: "biru",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 31,
    title: "Meadowheart",
    slug: null,
    price: "Rp 80.000",
    tema: "rustic",
    warna: "ungu",
    image: "/dummy-image/image-dummy-potrait.png",
  },
  {
    id: 32,
    title: "Hearthglow",
    slug: null,
    price: "Rp 80.000",
    tema: "rustic",
    warna: "coklat",
    image: "/dummy-image/image-dummy-potrait.png",
  },
];

export const temaFilters = [
  { label: "Semua Tema", value: "all" },
  { label: "Islamic", value: "islamic" },
  { label: "Modern", value: "modern" },
  { label: "Minimalis", value: "minimalis" },
  { label: "Mewah", value: "mewah" },
  { label: "Rustic", value: "rustic" },
];

export const warnaOptions = [
  { label: "Semua Warna", value: "all" },
  { label: "Coklat", value: "coklat" },
  { label: "Biru", value: "biru" },
  { label: "Pink", value: "pink" },
  { label: "Hijau", value: "hijau" },
  { label: "Ungu", value: "ungu" },
];
